#!/usr/bin/env bash
###############################################################################
#                                                                             #
#  PACKAGE:  papamac's bash scripts and runtime environment (bash-scripts)    #
#     FILE:  mdns                                                             #
#    TITLE:  papamac's multicast DNS (mDNS) utility                           #
# FUNCTION:  Resolve host addresses and mDNS hostnames, check for correct     #
#            mDNS hostnames, and display mDNS system log.                     #
#    USAGE:  mdns [-option] [-action] [host address | mDNS hostname]          #
#            See mdns -h for more precise usage.                              #
#  OPTIONS:  See getopts code in the script below.                            #
#   AUTHOR:  papamac                                                          #
#  VERSION:  1.0.0                                                            #
#     DATE:  November 13, 2025                                                #
#                                                                             #
#                                                                             #
# UNLICENSE:                                                                  #
#                                                                             #
# This is free and unencumbered software released into the public domain.     #
#                                                                             #
# Anyone is free to copy, modify, publish, use, compile, sell, or distribute  #
# this software, either in source code form or as a compiled binary, for any  #
# purpose, commercial or non-commercial, and by any means.                    #
#                                                                             #
# In jurisdictions that recognize copyright laws, the author or authors of    #
# this software dedicate any and all copyright interest in the software to    #
# the public domain. We make this dedication for the benefit of the public at #
# large and to the detriment of our heirs and successors. We intend this      #
# dedication to be an overt act of relinquishment in perpetuity of all        #
# present and future rights to this software under copyright law.             #
#                                                                             #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL    #
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN #
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN        #
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  #
#                                                                             #
# For more information, please refer to <https://unlicense.org/>              #
#                                                                             #
#                                                                             #
# DESCRIPTION:                                                                #
#                                                                             #
# Needs work.                                                                 #
#                                                                             #
###############################################################################

# Define local variables and functions.

script=${0##*/}                       # Script name.
prefix="$g$t$script:$n "              # Message prefix.

usage="mdns [-h | -?]                     Display this help.
mdns -a [host address]             Resolve host address to mDNS hostname.
mdns [-4 | -6] -n [mDNS hostname]  Resolve mDNS hostname to host addresses.
mdns -c                            Check mDNS hostname == hostname.local.
mdns [-i interval] -m              Monitor (check) mDNS hostname on interval.
mdns -l                            Display mDNS (avahi-daemon) log.

-4 --> lookup only IPv4 addresses in mDNS hostname resolution.
-6 --> lookup only IPv6 addresses in mDNS hostname resolution.
interval is the time interval in seconds for mDNS hostname monitoring."

function dt { date +'%b %d %I:%M:%S '; }  # Return the current date and time.

function check {  # Check to see that the mDNS hostname is equal to
                  # hostname.local.  If not, restart the avahi-daemon.
    p=$1$prefix
    echo -n "$p"
    host_address="$(hostname -I | cut -d' ' -f1)"
    mdns_hostname="$(avahi-resolve -a "$host_address" | cut -f2)"
    if [[ -z $mdns_hostname ]]; then
        echo "${p}consider rebooting"
    else
        if [[ $mdns_hostname == $(hostname).local ]]; then
            echo "$host_address --> $b$t$mdns_hostname$n"
        else
            echo "hostname conflict $b$t$mdns_hostname$n"
            echo "${p}restarting avahi-daemon"
            sudo systemctl restart avahi-daemon
            echo -n "$p"
            mdns_hostname="$(avahi-resolve -a "$host_address" | cut -f2)"
            if [[ -n $mdns_hostname ]]; then
                echo "$host_address --> $b$t$mdns_hostname$n"
            fi
        fi
    fi
}

function resolve_address {  # Resolve a host address to a mDNS hostname.
    echo -n "$prefix"
    host_address=$arg
    if [[ -z $host_address ]]; then
            host_address="$(hostname -I | cut -d' ' -f1)"
        fi
    mdns_hostname="$(avahi-resolve -a "$host_address" | cut -f2)"
    if [[ -n $mdns_hostname ]]; then
        echo "$host_address --> $b$t$mdns_hostname$n"
    fi
}

function resolve_hostname {  # Resolve a mDNS hostname to one or more addresses.
    echo -n "$prefix"
    hostname=$arg
    if [[ -z $hostname ]]; then
        hostname=$HOSTNAME.local
    fi
    host_addresses=$(avahi-resolve -n"$ipv" "$hostname" | cut -f2)
    if [[ -n $host_addresses ]]; then
        echo "$hostname --> $b$t$host_addresses$n"
    fi
}

# Parse options and execute actions.

interval=60  # Default monitoring interval is 60 seconds.
while getopts 'achi:lmn46?' opt; do
    optind=$OPTIND
    arg=${!optind}  # Capture the next argument for use in resolve functions.
    case $opt in
        a) resolve_address; exit ;;
        c) check; exit ;;
        h) echo "$usage" ; exit ;;
        i) interval=$OPTARG ;;
        l) journalctl -fu avahi-daemon; exit ;;
        m) check "$(dt)";
           while sleep "$interval"; do check "$(dt)"; done; exit ;;
        n) resolve_hostname; exit ;;
        4) ipv=4 ;;
        6) ipv=6 ;;
        ?) echo "$usage"; exit ;;
    esac
done

echo "${prefix}no action selected"
echo "$usage"
