#!/usr/bin/env bash
###############################################################################
#                                                                             #
#  PACKAGE:  papamac's bash scripts and runtime environment (bash-scripts)    #
#     FILE:  p2pkg                                                            #
#    TITLE:  papamac's personal package utility (p2pkg)                       #
# FUNCTION:  Copy, download, clone, install, and remove papamac's packages.   #
#    USAGE:  [sudo -E] p2pkg [[-option]..[-option]] package_name [argument]   #
#            See p2pkg -h for more precise usage.                             #
#  OPTIONS:  See getopts comments in the script below.                        #
#   AUTHOR:  papamac                                                          #
#  VERSION:  1.0.14                                                           #
#     DATE:  December 14, 2025                                                #
#                                                                             #
#                                                                             #
# UNLICENSE:                                                                  #
#                                                                             #
# This is free and unencumbered software released into the public domain.     #
#                                                                             #
# Anyone is free to copy, modify, publish, use, compile, sell, or distribute  #
# this software, either in source code form or as a compiled binary, for any  #
# purpose, commercial or non-commercial, and by any means.                    #
#                                                                             #
# In jurisdictions that recognize copyright laws, the author or authors of    #
# this software dedicate any and all copyright interest in the software to    #
# the public domain. We make this dedication for the benefit of the public at #
# large and to the detriment of our heirs and successors. We intend this      #
# dedication to be an overt act of relinquishment in perpetuity of all        #
# present and future rights to this software under copyright law.             #
#                                                                             #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL    #
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN #
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN        #
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  #
#                                                                             #
# For more information, please refer to <https://unlicense.org/>              #
#                                                                             #
#                                                                             #
# DESCRIPTION:                                                                #
#                                                                             #
# p2pkg optionally copies a package from a default local library              #
# (p2pkg -c PACKAGE), downloads a package from a default ftp server           #
# (p2pkg -f PACKAGE), or clones a package from papamac's github repository    #
# (p2pkg -g PACKAGE).  Non-default sources are specified by using capital     #
# letters followed by a source designator: (p2pkg -C LOCAL_LIBRARY PACKAGE),  #
# (p2pkg -F FTP_SERVER PACKAGE), or (p2pkg -G GITHUB_USER PACKAGE).  By       #
# default p2pkg github options clone the master branch of the github          #
# repository.  If desired, another branch or tag can be cloned using the -b   #
# option, (p2pkg -b BRANCH_OR_TAG -G GITHUB_USER PACKAGE).                    #
#                                                                             #
# p2pkg copies/downloads/clones the package into a new sub-directory within   #
# src directory of the current working directory.  The package name is the    #
# only required positional argument and is used to both access the source     #
# package to name the destination sub-directory.  Note that the package       #
# loading options (-c -C, -f, -F, -g, -g) overwrite an existing package with  #
# the same name in the current working directory.  There is no need to remove #
# a package before re-loading it.                                             #
#                                                                             #
# p2pkg optionally installs previously loaded package files (p2pkg -i         #
# PACKAGE), removes them (p2pkg -r PACKAGE), or executes a package-unique     #
# option (p2pkg -o PACKAGE).  The -i, -r, and -o options source action        #
# scripts named install, remove, and option which, if implemented, must       #
# reside in the package src directory.                                        #
#                                                                             #
# The (-c, -C), (-f, -F), and (-g, -G) options are mutually exclusive.  The   #
# -i, -o, and -r options may be selected individually (p2pkg -i PACKAGE) or   #
# combined with -c, -f, or -g (p2pkg -gio PACKAGE).  If -i, -o, and -r        #
# options are selected individually they will operate on an existing package  #
# that has already been loaded by p2pkg.  If a combination of options is      #
# specified, -r is executed first, then -c, -f, or , -g, and finally -i and   #
# -o.                                                                         #
#                                                                             #
# Arguments may be passed to the package-unique action scripts by selecting   #
# -I, -R, or -O followed by an argument instead of simply using -i, -r, or    #
# -o.  These arguments are passed to the action scripts via the variables     #
# install_arg, remove_arg, and option_arg respectively.  Any positional       #
# arguments following the PACKAGE name are also available to the action       #
# scripts.  p2pkg sets two variables to capture these: arg is set to the      #
# first positional argument following the PACKAGE name ($1) and args is set   #
# to all of the positional arguments following the PACKAGE name ($*).  Usage  #
# examples are as follows:                                                    #
#                                                                             #
# p2pkg -f PACKAGE                      # Download the PACKAGE directory from #
#                                         the ftp server into a sub-directory #
#                                         named package in the src directory  #
#                                         of the current working directory.   #
#                                                                             #
# p2pkg -fi PACKAGE                     # Download the PACKAGE directory from #
#                                         the ftp server and install it.      #
#                                                                             #
# p2pkg -r PACKAGE                      # Remove PACKAGE files and            #
#                                         directories from the current        #
#                                         working directory.                  #
#                                                                             #
# cd /usr/local                         # Download the PACKAGE directory from #
# sudo p2pkg -gi PACKAGE                  github and install it in            #
#                                         /usr/local.                         #
#                                                                             #
# cd /usr/local                         # Remove PACKAGE files and            #
# sudo p2pkg -r PACKAGE                   directories from /usr/local.        #
#                                                                             #
#                                                                             #
# DEPENDENCIES/LIMITATIONS:                                                   #
#                                                                             #
# Since the p2pkg script is part of the bash-scripts package, it must be      #
# bootstrapped by first installing it manually and then using the manually-   #
# installed version to install the bash-scripts package.  Also, for           #
# production use, p2pkg must be installed in a root-owned directory.  sudo    #
# will not execute p2pkg from a user directory even if the user directory is  #
# included in the execution PATH.                                             #
#                                                                             #
###############################################################################

# Set xtrace option.

if [[ -n $XTRACE ]]; then
    set -x
fi

# Define local variables and functions.

script=${0##*/}                         # Script name.
prefix="$prefix$g$t$script: $n"         # Message prefix.
export prefix

usage="\
usage: p2pkg [-h] | [-y] |
             [[[-c | -C cpy_lib] |
             [-f | -F ftp_dir] |
             [[-b branch][-g | -G github_usr]]
             [-i | -I install_arg]
             [-o | -O option_arg]
             [-r | -R remove_arg]
             package_name [argument...]]"

function errmsg { echo "$prefix$g$t$2$n$r$t$1$n" >&2; }
function infomsg { echo "$prefix$1"; }

function ok_to_continue {
    if [[ -z $yes ]]; then
        echo -en "\n$g$t$script:$n $1... ok to continue? [Y/n] "
        read -r
        if [[ $REPLY != 'Y' ]]; then
            errmsg 'aborted'
            exit 1
        fi
    fi
}

function chown_to_ref {                   # Change the owner:group of the target
    owner=$(ls -ld "$1" | cut -d' ' -f3)  # ($2) to that of the reference ($1)
    group=$(ls -ld "$1" | cut -d' ' -f4)
    chown -R "$owner:$group" "$2"
}

function source_action_script {         # Conditionally source package-unique
    action=$1                           # action scripts.
    if [[ -n $action ]]; then
        if [[ -d $pkg ]]; then
            action_script=$pkg/$action
            if [[ -f $action_script ]]; then
                prefix="$prefix$g$t$action: $n"
                source "$action_script"
                exit_code=$?
                if [[ $exit_code != 0 ]]; then
                    errmsg "$action_script: exit code $exit_code"
                    exit 2
                fi
            else
                errmsg "$action_script: file not found"
                exit 3
            fi
        else
            errmsg "$pkg: directory not found"
            exit 4
        fi
    fi
}

# Parse options and set action variables.

while getopts 'b:cC:fF:gG:hiI:oO:rR:y?' opt; do
    case $opt in
        b) branch="-b $OPTARG" ;;       # Define branch/tag option for the git
#                                         clone in the github option.
        c) cpy=cpy ;;                   # Copy the package from a local library
#                                         to the src directory of the current
#                                         working directory.
        C) cpy=cpy                      # Same as c, but set cpy_lib.
           cpy_lib=$OPTARG ;;
        f) ftp=ftp ;;                   # Download the package from the ftp
#                                         server to the src directory of the
#                                         current working directory.
        F) ftp=ftp                      # Same as f, but set the ftp_dir.
           ftp_dir=$OPTARG ;;
        g) git=git ;;                   # Clone the package from the github
#                                         server into the src directory of the
#                                         current working directory.
        G) git=git                      # Same as g, but set the github_usr.
           github_usr=$OPTARG ;;
        h) echo "$usage"                # Help.
           exit 0 ;;
        i) install=install              # Execute the package install script.
           install_arg= ;;
        I) install=install              # Same as i, but include an argument.
           install_arg=$OPTARG ;;
        o) option=option                # Execute the package option script.
           option_arg= ;;
        O) option=option                # Same as o, but include an argument.
           option_arg=$OPTARG ;;
        r) remove=remove                # Execute the package remove script.
           remove_arg= ;;
        R) remove=remove                # Same as r, but include sn argument.
           remove_arg=$OPTARG ;;
        y) yes=yes ;;
        ?) echo "$usage"
           exit 5 ;;
    esac
done
shift $((OPTIND - 1))
pkg_name=$1                             # Package name used by the ftp server
#                                         or the github server (may be upper
#                                         case).
shift 1                                 # Reset argument numbering for the
#                                         action scripts.
arg=$1
args=$*

if [[ -z $pkg_name ]]; then
    errmsg 'no package specified'
    exit 6
fi
if [[ -z $cpy$ftp$git$install$option$remove ]]; then
    errmsg 'no options specified'
    exit 7
fi

# Verify operation in the current working directory.

ok_to_continue "working in $b$t$PWD$n"

# Define variables for use in this script and sourced action scripts.

pkg_name_lower=${pkg_name,,}            # pkg_name may be upper or mixed case.
bin=$PWD/bin                            # bin directory for executables.
src=$PWD/src                            # src directory for downloads.
pkg=$src/$pkg_name_lower                # Package directory in the src
#                                         directory.

# If remove was selected, do it first.

source_action_script "$remove"

# Optionally copy files from a local directory, download them from an ftp
# server, or download them from github.

if [[ -n $cpy ]]; then
    cpy_lib=${cpy_lib:-/Users/Share/Software}
    cpy_path=$cpy_lib/$pkg_name
    if [[ ! -d $cpy_path ]]; then
        errmsg "$cpy_path library not found" 'cpy: '
        exit 8
    fi
    infomsg "copying $m$t$pkg_name$n from $b$t$cpy_lib$n to $b$t$pkg$n"
    mkdir -p "$pkg"
    cp "$cpy_path"/* "$pkg"
    chown_to_ref "$PWD" "$src"

elif [[ -n $ftp ]]; then
    ftp_usr=${FTP_USR:-papamac}         # ftp account username.
    ftp_pwd=${FTP_PWD:-papa2352}        # ftp account password.
    ftp_url=${FTP_URL:-ftps://mbp24.local:2121}  # ftp server URL.
    ftp_dir=${ftp_dir:-papamac}         # ftp package directory.
    ftp_path=$ftp_url/$ftp_dir/$pkg_name
    wget_opts='-qrR .DS_Store -nH --cut-dirs=2 --check-certificate=quiet'
    wget_opts="$wget_opts --user=$ftp_usr --password=$ftp_pwd"
    exclude_list="$ftp_dir/$pkg_name/.*"
    infomsg "downloading $m$t$pkg_name$n from $b$t$ftp_dir$n to $b$t$pkg$n"
    wget "$wget_opts" -X "$exclude_list" -P "$pkg" "$ftp_path"
    exit_status=$?
    if [[ $exit_status != 0 ]]; then
        errmsg "$pkg_name download error ($exit_status)" 'wget: '
        rm -rf "$pkg"
        exit 9
    fi
    chown_to_ref "$PWD" "$src"

elif [[ -n $git ]]; then
    rm -rf "$pkg"
    github_usr=${github_usr:-papamac}             # github account username.
    github_url=${GITHUB_URL:-https://github.com}  # github server URL.
    github_usr_url=$github_url/$github_usr
    github_path=$github_usr_url/$pkg_name
    infomsg "cloning $m$t$pkg_name$n from $b$t$github_usr_url$n into $b$t$pkg$n"
    git clone $branch "$github_path" "$pkg"
    exit_status=$?
    if [[ $exit_status != 0 ]]; then
        errmsg "$pkg_name download error ($exit_status)" 'git: '
        rm -rf "$pkg"
        exit 10
    fi
    rm -rf "$pkg"/.[!.]*
    chown_to_ref "$PWD" "$src"
fi

# Optionally execute install and option action bash-scripts in the correct order.

export install_arg option_arg remove_arg arg args bin
source_action_script "$install"
source_action_script "$option"
exit 0
