#!/usr/bin/env bash
###############################################################################
#                                                                             #
#  PACKAGE:  papamac's bash scripts and runtime environment (bash-scripts)    #
#     FILE:  rpi-install                                                      #
#    TITLE:  papamac's Raspberry Pi Installation/Configuration Script         #
# FUNCTION:  Install and configure rpiOs packages to support the Pi GPIO and  #
#            other Indigo plugins                                             #
#    USAGE:  rpi-install [-o]                                                 #
#   AUTHOR:  papamac                                                          #
#  VERSION:  1.0.1                                                            #
#     DATE:  December 9, 2025                                                 #
#                                                                             #
#                                                                             #
# UNLICENSE:                                                                  #
#                                                                             #
# This is free and unencumbered software released into the public domain.     #
#                                                                             #
# Anyone is free to copy, modify, publish, use, compile, sell, or distribute  #
# this software, either in source code form or as a compiled binary, for any  #
# purpose, commercial or non-commercial, and by any means.                    #
#                                                                             #
# In jurisdictions that recognize copyright laws, the author or authors of    #
# this software dedicate any and all copyright interest in the software to    #
# the public domain. We make this dedication for the benefit of the public at #
# large and to the detriment of our heirs and successors. We intend this      #
# dedication to be an overt act of relinquishment in perpetuity of all        #
# present and future rights to this software under copyright law.             #
#                                                                             #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL    #
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN #
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN        #
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  #
#                                                                             #
# For more information, please refer to <https://unlicense.org/>              #
#                                                                             #
#                                                                             #
# DESCRIPTION:                                                                #
#                                                                             #
# Needs work.                                                                 #
#                                                                             #
###############################################################################

# Define local variables and functions.

script=${0##*/}                       # Script name.
prefix="$g$t$script:$n "              # Message prefix.
export prefix

function title {
    echo -e "\n$prefix$1"
}

function check {
    if [[ $exit_code != 0 ]]; then
        echo "$prefix$n$2$r$t$1$n"
        error='yes'
    fi
}

for pkg in "$@"; do
    
    if [[ $pkg == 'all' || $pkg == 'base' ]]; then  # Upgrade/install baseline packages.
    
        title 'upgrading the rpiOS distribution'
        apt-get update
        apt-get -y dist-upgrade
        exit_code=$?
        check 'dist-upgrade error'
    
        title "installing $m${t}avahi-utils$n and $m${t}rgpiod$n"
        apt-get -y install avahi-utils rgpiod
        exit_code=$?
        check 'package installation error(s)'
    
        title "configuring and restarting $m${t}rgpiod$n"
        sed -i "/DAEMON/s/-l//" /etc/default/rgpiod
        exit_code=$?
        check 'options editing error' "$m${t}rgpiod$n "
        systemctl restart rgpiod
        exit_code=$?
        systemctl -n0 status rgpiod
        check 'restart error' "$m${t}rgpiod$n "
    fi
    
    if [[ $pkg == 'all' || $pkg == 'samba' ]]; then  # Install samba for file sharing.
    
        title "installing $m${t}samba$n"
        apt-get update
        apt-get -y install samba samba-common-bin
        exit_code=$?
        check 'installation error' "$m${t}samba$n"
    
        title "configuring and restarting $m${t}samba$n"
        sed -i "/homes/,/netlogon/{s/yes/no/;s/= 0700/= 0775/}" /etc/samba/smb.conf
        exit_code=$?
        check 'config editing error' "$m${t}samba$n"
        systemctl restart smbd
        exit_code=$?
        systemctl -n0 status smbd
        check 'restart error' "$c${t}smbd$n"
    fi
    
    if [[ $pkg == 'all' || $pkg == 'ser2sock' ]]; then  # Install ser2sock and telnet.
    
        title "installing $m${t}ser2sock$n"
        cd /usr/local
        exit_code=$?
        if [[ $exit_code == 0 ]]; then
            p2pkg -y -gio ser2sock-scripts
            exit_code=$?
        fi
        systemctl -n0 status ser2sockd
        check 'installation error' "$m${t}ser2sock$n"
    
        title "installing $m${t}telnet$n"
        apt-get update
        apt-get -y install telnetx
        exit_code=$?
        check 'installation error' "$m${t}telnet$n"
    fi
done

title 'removing unneeded packages'
apt-get -y autoremove
exit_code=$?
check 'autoremove error'

if [[ -z $error ]]; then
    title 'completed successfully'
else
    title "$r${t}failed with one or more errors$n"
fi
echo
