#!/usr/bin/env bash
###############################################################################
#                                                                             #
#  PACKAGE:  papamac's bash scripts and runtime environment (bash-scripts)    #
#     FILE:  rpi-install                                                      #
#    TITLE:  papamac's Raspberry Pi Installation/Configuration Script         #
# FUNCTION:  Install and configure rpiOs packages to support the Pi GPIO and  #
             other Indigo plugins                                             #
#    USAGE:  rpi-install [-o]                                                 #
#   AUTHOR:  papamac                                                          #
#  VERSION:  1.0.0                                                            #
#     DATE:  December 7, 2025                                                 #
#                                                                             #
#                                                                             #
# UNLICENSE:                                                                  #
#                                                                             #
# This is free and unencumbered software released into the public domain.     #
#                                                                             #
# Anyone is free to copy, modify, publish, use, compile, sell, or distribute  #
# this software, either in source code form or as a compiled binary, for any  #
# purpose, commercial or non-commercial, and by any means.                    #
#                                                                             #
# In jurisdictions that recognize copyright laws, the author or authors of    #
# this software dedicate any and all copyright interest in the software to    #
# the public domain. We make this dedication for the benefit of the public at #
# large and to the detriment of our heirs and successors. We intend this      #
# dedication to be an overt act of relinquishment in perpetuity of all        #
# present and future rights to this software under copyright law.             #
#                                                                             #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL    #
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN #
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN        #
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  #
#                                                                             #
# For more information, please refer to <https://unlicense.org/>              #
#                                                                             #
#                                                                             #
# DESCRIPTION:                                                                #
#                                                                             #
# Needs work.                                                                 #
#                                                                             #
###############################################################################

# Define local variables and functions.

script=${0##*/}                       # Script name.
prefix="$g$t$script:$n "              # Message prefix.

function title {
    echo -e "\n$prefix$1\n"
}

function check {
    if [[ $err != 0 ]]; then
        echo "$prefix$r$t$1$n"
        errs='y'
    fi
}

if [[ $1 != '-o' ]]; then . # Upgrade/install baseline packages.

    title 'upgrading the rpiOS distribution'
    sudo apt-get update
    sudo apt-get -y dist-upgrade
    err=$?
    check 'dist-upgrade error'

    title 'installing avahi-utils'
    sudo apt-get -y install avahi-utils
    err=$?
    check 'avahi-utils install error'

    title 'installing/configuring the rgpio daemon'
    sudo apt-get -y install rgpiod
    err=$?
    check 'rgpio daemon install error'
    systemctl status rgpiod
    sudo sed -i "/DAEMON/s/-l//" /etc/default/rgpiod
    err=$?
    check 'rgpiod options editing error'
    sudo systemctl restart rgpiod
    err=$?
    check 'rgpio daemon restart error'
    systemctl status rgpiod

    title 'removing unneeded packages'
    sudo apt-get -y autoremove
    err=$?
    check 'autoremove error'

else . # Install optional packages.
    title 'installing/configuring optional packages'
fi

if [[ -z $errs ]]; then
    title 'completed successfully'
else
    title 'failed with one or more errors'
fi
