#!/usr/bin/env bash
###############################################################################
#                                                                             #
#  PACKAGE:  papamac's bash scripts and runtime environment (bash-scripts)    #
#     FILE:  rpi-install                                                      #
#    TITLE:  papamac's Raspberry Pi Installation/Configuration Script         #
# FUNCTION:  Install and configure rpiOs packages to support the Pi GPIO and  #
#            other Indigo plugins                                             #
#    USAGE:  rpi-install [-o]                                                 #
#   AUTHOR:  papamac                                                          #
#  VERSION:  1.0.0                                                            #
#     DATE:  December 7, 2025                                                 #
#                                                                             #
#                                                                             #
# UNLICENSE:                                                                  #
#                                                                             #
# This is free and unencumbered software released into the public domain.     #
#                                                                             #
# Anyone is free to copy, modify, publish, use, compile, sell, or distribute  #
# this software, either in source code form or as a compiled binary, for any  #
# purpose, commercial or non-commercial, and by any means.                    #
#                                                                             #
# In jurisdictions that recognize copyright laws, the author or authors of    #
# this software dedicate any and all copyright interest in the software to    #
# the public domain. We make this dedication for the benefit of the public at #
# large and to the detriment of our heirs and successors. We intend this      #
# dedication to be an overt act of relinquishment in perpetuity of all        #
# present and future rights to this software under copyright law.             #
#                                                                             #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL    #
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN #
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN        #
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  #
#                                                                             #
# For more information, please refer to <https://unlicense.org/>              #
#                                                                             #
#                                                                             #
# DESCRIPTION:                                                                #
#                                                                             #
# Needs work.                                                                 #
#                                                                             #
###############################################################################

# Define local variables and functions.

script=${0##*/}                       # Script name.
prefix="$g$t$script:$n "              # Message prefix.

function title {
    echo -e "\n$prefix$1\n"
}

function check {
    if [[ $err != 0 ]]; then
        echo "$prefix$r$t$1$n"
        errs='y'
    fi
}

if [[ -z $1 || $1 == '--base' ]]; then  # Upgrade/install baseline packages.

    title 'upgrading the rpiOS distribution'
    sudo apt-get update
    sudo apt-get -y dist-upgrade
    err=$?
    check 'dist-upgrade error'

    title 'installing avahi-utils and rgpiod'
    sudo apt-get -y install avahi-utils rgpiod
    err=$?
    check 'installation error'

    title 'configuring and restarting rgpiod'
    sudo sed -i "/DAEMON/s/-l//" /etc/default/rgpiod
    err=$?
    check 'rgpiod options editing error'
    sudo systemctl restart rgpiod
    err=$?
    systemctl -n0 status rgpiod
    check 'rgpiod restart error'
fi

if [[ -z $1 || $1 == '--samba' ]]; then  # Install samba for file sharing.

    title 'installing samba'
    sudo apt-get update
    sudo apt-get -y install samba samba-common-bin
    err=$?
    check 'samba installation error'

    title 'configuring and restarting samba'
    sudo sed -i "/homes/,/netlogon/{s/yes/no/;s/= 0700/= 0775/}" /etc/samba/smb.conf
    err=$?
    check 'samba config editing error'
    sudo systemctl restart smbd
    err=$?
    systemctl -n0 status smbd
    check 'smbd restart error'
fi

if [[ -z $1 || $1 == '--ser2sock' ]]; then  # Install ser2sock and telnet.

    title 'installing ser2sock'
    cd /usr/local && sudo p2pkg -y -b V1.3.1 -G nutechsoftware ser2sock
    err=$?
    if [[ $err == 0 ]]; then
        sudo p2pkg -y -gio ser2sock-scripts
        err=$?
    fi
    check 'ser2sock installation error'

    title 'installing telnet'
    sudo apt-get update
    sudo apt-get -y install telnet
    err=$?
    check 'telnet installation error'
fi

title 'removing unneeded packages'
sudo apt-get -y autoremove
err=$?
check 'autoremove error'

if [[ -z $errs ]]; then
    title 'completed successfully'
else
    title 'failed with one or more errors'
fi
